### ISSUE TITLE
Resolve middleware via the container

### ISSUE THREAD

**Issue by IsraelOrtuno** [roach-php/core#10]
I can't find where Middlewares are resolved. I would like to add a few parameters to the underlying Browsershot instance since the URL I am trying to parse does not render a few items until they get into the viewport.

```php
        $this->app->bind(ExecuteJavascriptMiddleware::class, function () {
            return new ExecuteJavascriptMiddleware(
                app(LoggerInterface::class),
                function ($url) {
                    return Browsershot::url($url)->windowSize(1900, 50000)
                        ->setIncludePath('/Users/israel/.nvm/versions/node/v14.17.5/bin');
                }
            );
        });
```

Seems like the ExecuteJavascriptMiddleware class is not resolved via the Laravel Container so I can't overwrite it. Since this is a framework agnostic package, how can I do this? Class is also `final` so can't extend from the main ExecuteJavascriptMiddleware class and just update its behaviour which could be great.

**Comment by IsraelOrtuno** [comment]
Nevermind found it myself https://roach-php.dev/docs/dependency-injection

**Comment by ksassnowski** [comment]
Just to clarify, all middleware _should_ already be resolved out of the container. So registering a binding for `ExecuteJavascriptMiddleware` in your service provider should work. Can you confirm that it did? 

If you’re using Roach inside a Laravel project, I recommend using the [Laravel adapter](https://roach-php.dev/laravel) which takes care of registering all the necessary bindings and makes Roach use Laravel’s container.

Also, the `ExecuteJavascriptMiddleware` exposes all [configuration options](https://roach-php.dev/docs/downloader-middleware#configuration-options-2) that the underlying `spatie/browsershot` package exposes. So you could also configure the `includePath` that way. Not sure about the window size, though.
