### ISSUE TITLE
This library is no longer maintained?

### ISSUE THREAD

**Issue by wengooooo** [roach-php/core#138]
Is this project no longer maintained and no one has updated it for over a year?

**Comment by ksassnowski** [comment]
The last commit has literally been 3 days ago.

That being said, I consider the library to be mostly feature complete. Most feature requests (like middleware) can easily be implemented in user land. I am working on more complete version of a Proxy middleware than #69 but there's not really an ETA on that.

**Comment by andruu** [comment]
Any word on the proxy middleware? Trying to use the ZenRows service
