### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by ntaylor-86** [roach-php/core#158]
**Description**
Hello, I'm sure this is possible I just couldn't find a reference to it in the docs.

How do you tell Roach to accept self signed certificates?

Cheers.

**Comment by ksassnowski** [comment]
You can configure [options](https://docs.guzzlephp.org/en/stable/request-options.html) on the underlying Guzzle request using `$request->addOption(string $name, mixed $value)`. 

So you could write a request middleware that sets the `verify` option on each outgoing request and then use that as a [downloader middleware](https://roach-php.dev/docs/downloader-middleware) in you spider.

```php
use RoachPHP\Downloader\Middleware\RequestMiddlewareInterface;
use RoachPHP\Http\Request;
use RoachPHP\Support\Configurable;

final class WithoutCertificateValidation implements RequestMiddlewareInterface
{
    use Configurable;

    public function handleRequest(Request $request): Request
    {
        // Completely disable SSL certificate verification.
        return $request->addOption('verify', false);
    }
}
```

**Comment by ntaylor-86** [comment]
Thanks @ksassnowski 🙏
