### ISSUE TITLE
Scraping multiple elements within a page and relative queries is not available

### ISSUE THREAD

**Issue by wett1988** [roach-php/core#19]
Hi! Now package is allow scraping list of single pages.

But what if we need to repeatedly select a list of items within a page and do an additional filter on each of them? For example:

```
public function parse(Response $response): Generator
{
  $data = $response->filter('.preview');
  
  foreach ($data as $item) {  
      $cover = $item->filter('img')->attr('src');
      $number = $tem->filter('span:nth-of-type(1)')->text();
      $published = $item->filter('span.published')->text();
      
      yield $this->item(compact('cover', 'number', 'published'));
  } 
}
```

Here I want to select a list of items on every page by the general `.preview` filter, and then make an additional filter for each of `$item` to get the data I want.

At the moment, as I understand it, the package does not support such functionality, although in `scrapy` [it is possible](https://docs.scrapy.org/en/latest/topics/selectors.html#nesting-selectors) and is a powerful tool for working with page data.

**Comment by ksassnowski** [comment]
Do you have an actual page you’re trying to crawl where this doesn’t work? Because this should work pretty much like your example.

**Comment by ksassnowski** [comment]
Ah I see what the problem is. Inside the `foreach` loop, `$item` is an actual `DOMElement` instance, not a crawler. You can still do this, but you have to use a slightly different syntax.

```php
use Symfony\Component\DomCrawler\Crawler;

public function parse(Response $response): Generator
{
    $items = $response->filter('.preview')->each(function (Crawler $crawler) {
        return [
            'cover' => $crawler->filter('img')->attr('src'),
            'number' => $crawler->filter('span:nth-of-type(1)')->text(),
            'published' => $crawler->filter('span.published')->text(),
        ];
    });

    foreach ($items as $item) {
        yield $this->item($item);
    }
}
```

This is how the underlying `symfony/dom-crawler` package works and has tripped me up a couple of times, too 😅 (https://symfony.com/doc/current/components/dom_crawler.html). You lose a bit of the laziness as you have to build every item first before yielding them one by one. Maybe I can improve this behavior some day.

**Comment by wett1988** [comment]
> Ah I see what the problem is. Inside the `foreach` loop, `$item` is an actual `DOMElement` instance, not a crawler.

Yes, that's what caused the problem - `filter` returns `DOMElement` which cannot be further manipulated.

> You can still do this, but you have to use a slightly different syntax.

Yes, your code works exactly as I need it to! Thank you very much for your help and good luck in developing this excellent package!

**Comment by joalea** [comment]
Thanks this really helped me! Would be great if you added this to the documentation

**Comment by Xoshbin** [comment]
Thank you guys, This helped a lot.
I have an issue, when I save the item in to the database it saves only the first array.
I thought it's supposed to run the itemProcessors each time I yield the item.


```
    /**
     * @return Generator<ParseResult>
     */
    public function parse(Response $response): Generator
    {
        $posts = $response
            ->filter('main > div.container-fluid > div.row > div.col-md-9 > div.row')->each(function (Crawler $crawler) {
                return [
                    'title' => $crawler->filter('div.col-md-4 > a > div.card > div.card-body > h5.card-title')->text(),
                    'excerpt' => $crawler->filter('div.col-md-4 > a > div.card > div.card-body > p')->last()->text(),
                    'url' => $crawler->filter('div.col-md-4 > a')->attr('href'),
                    'image_url' => $crawler->filter('div.col-md-4 > a > div.card > img')->attr('src'),
                    'date' => $crawler->filter('div.col-md-4 > a > div.card > div.card-body > p > small')->text(),
                    'source' => $crawler->filter('div.col-md-4 > a > div.card > div.card-body > p > a > span')->text(),
                ];
            });

        foreach ($posts as $post) {
            yield $this->item($post);    //here I suppose it should run item processor for each item???
        }
    }
```

**Comment by ksassnowski** [comment]
It should. Have you inspected the `$posts` variable to see how many entries it contains?

**Comment by Xoshbin** [comment]
Thank @ksassnowski 
I just found that I had an error somewhere else.
