### ISSUE TITLE
How to pass data to the spider?

### ISSUE THREAD

**Issue by hamedgasemi200** [roach-php/core#30]
I need to pass data to the spider about the previous request.

To be specific, I want to store which sites, have the link of the current site in their content. But I can not send any extra information to my crawler like the information about the previous request.

I wanted something like this:

```
    \RoachPHP\Roach::startSpider(MySpider::class,
        new \RoachPHP\Spider\Configuration\Overrides([
            'startUrls' => 'https://masaf.ir',
            'reference' => 'https://masaf.ir'
        ]),
    );
```

But Overrides only overrides the conventional spider's configuration ):

___

In other and simple words, I want to make the spider configurable somehow, and send data to it.

**Comment by ksassnowski** [comment]
Quick heads up that this is currently being worked on.

**Comment by ksassnowski** [comment]
The 1.0 release provides a new `$context` parameter to the `startSpider` method that accepts arbitrary data. Check out [the docs](https://roach-php.dev/docs/spiders#passing-additional-context-to-spiders) for more details.
