### ISSUE TITLE
Defining Different Parse Methods does not work

### ISSUE THREAD

**Issue by henryonsoftware** [roach-php/core#31]
I have a spider which get some links from the response.

I call `$this->request('GET', $fullUrl, 'parseSportDetailPage');` on the `parse` method and also define
the `parseSportDetailPage` method.

```
public function parseSportDetailPage(Response $response)
{
    dd(123);
}
```

But it's not been reached, I tried to dd(123) inside `parseSportDetailPage` and it didn't stop, nothing thrown, no logs also.

**Comment by bansalvinay** [comment]
@henryonsoftware Can you post here what was the problem that you found? I'm facing exact same issue.
