### ISSUE TITLE
[Laravel Sail] ExcecuteJavascriptMiddleware not firing

### ISSUE THREAD

**Issue by andyscraven** [roach-php/core#53]
I am wanting to use this Middleware but it is not firing. I had an issue as I am using Laravel Sail on an M1 Mackbook and installing puppeteer had issues due to chromium not being arm64 ready:

`The chromium binary is not available for arm64.`

 so I did the following.

I installed spatie/browsershot and ran

`sail PUPPETEER_EXPERIMENTAL_CHROMIUM_MAC_ARM=1 npm i puppeteer`

and everything seemed to install correctly but the ExcecuteJavascriptMiddleware doesn't appear to being called so I still get the:

`<noscript>You need to enable JavaScript to run this app.</noscript>\n`

version of the page returned.

I put breakpoints in ExcecuteJavascriptMiddleware but they never fire.

am I doing something wrong or missed a step?

I am using the Laravel Adaptor so thought the Middleware was already injected in to the Container, am I wrong?

**Comment by andyscraven** [comment]
I'm an idiot.  I forgot to add it to:

`    public array $downloaderMiddleware = [
        RequestDeduplicationMiddleware::class,
        ExecuteJavascriptMiddleware::class
    ];
`

**Comment by Azmandios** [comment]
I think the arm architecture of chrome does not correctly call the executable file. 
I don't have the right device for the test. 
But I found a link for your problem:

[https://linguinecode.com/post/how-to-fix-m1-mac-puppeteer-chromium-arm64-bug](url)

**Comment by ksassnowski** [comment]
I'm not familiar with Laravel Sail, unfortunately. So I can't be of much help here 😞
