### ISSUE TITLE
Overriding Not Working

### ISSUE THREAD

**Issue by sinarahmany** [roach-php/core#79]
Hi, hope all is well,
I`m trying to pass the URL dynamically using overriding but it`s not working and the response is null.
Thank you

```
Roach::startSpider(
            LoremIpsumSpider::class,
            new Overrides(startUrls: ['https://sinarahmannejad.com']),
        );

        $result = Roach::collectSpider(LoremIpsumSpider::class);
```

**Comment by beunwa** [comment]
same problem here

**Comment by beunwa** [comment]
my bad it works fine, but dont forget to also provide Overrides in your Roach::collectSpider call

**Comment by ksassnowski** [comment]
Just to be clear, you're supposed to _either_ call `startSpider` _or_ `collectSpider`.https://roach-php.dev/docs/spiders/#retrieving-scraped-items-after-a-run
