### ISSUE TITLE
 Argument #1 ($request) must be of type RoachPHP\Http\Request, string given

### ISSUE THREAD

**Issue by andreaskviby** [roach-php/core#83]
Hey,
I have no idea why I get this error but it started when starting the Spiders from a Laravel Job instead of directly from the kernel.php file.

TypeError: RoachPHP\Core\Engine::scheduleRequest(): Argument #1 ($request) must be of type RoachPHP\Http\Request, string given, called in /home/forge/clarken.nomess.se/vendor/roach-php/core/src/Core/Engine.php on line 65 and defined in /home/forge/clarken.nomess.se/vendor/roach-php/core/src/Core/Engine.php:125

**Comment by ksassnowski** [comment]
I'll need a bit more information to debug this. Can you set up a repository that reproduces the error?
