### ISSUE TITLE
Conflict with Laravel 9

### ISSUE THREAD

**Issue by teandr** [roach-php/core#84]
Hello.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires roach-php/core ^2.0 -> satisfiable by roach-php/core[2.0.0].
    - roach-php/core 2.0.0 requires monolog/monolog ^3.1 -> found monolog/monolog[3.1.0, 3.2.0, 3.3.0, 3.3.1] but the package is fixed to 2.9.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by teandr** [comment]
Laravel 10

Problem 1
    - roach-php/core[1.0.0, ..., 1.1.1] require monolog/monolog ^2.3 -> found monolog/monolog[2.3.0, ..., 2.9.1] but the package is fixed to 3.3.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - roach-php/core 2.0.0 requires sebastian/version ^3.0 -> found sebastian/version[3.0.0, 3.0.1, 3.0.2] but the package is fixed to 4.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - roach-php/laravel 2.0.0 requires roach-php/core ^1.0 || ^2.0 -> satisfiable by roach-php/core[1.0.0, 1.1.0, 1.1.1, 2.0.0].
    - Root composer.json requires roach-php/laravel ^2.0 -> satisfiable by roach-php/laravel[2.0.0].

**Comment by ksassnowski** [comment]
Thanks for reporting this. I just released two new versions that should fix this issue.
